import { useState, useEffect } from "react";
import { Outlet, useLocation } from "react-router";
// @ts-expect-error - Route types are generated by React Router
import type { Route } from "../+types/admin";
import { InputAdornment, TableHead, TableBody, TableRow } from "@mui/material";
import {
  Dashboard as DashboardIcon,
  People as PeopleIcon,
  Computer as ComputerIcon,
  Description as DescriptionIcon,
  Settings as SettingsIcon,
  PersonAdd as PersonAddIcon,
  AddCircle as AddCircleIcon,
  Search as SearchIcon,
  Edit as EditIcon,
  Visibility as VisibilityIcon,
  Delete as DeleteIcon,
  PeopleOutline as PeopleOutlineIcon,
  Devices as DevicesIcon,
  Schedule as ScheduleIcon,
  Favorite as FavoriteIcon,
} from "@mui/icons-material";
import { userApi, type User } from "../../api/userApi";
import { deviceApi, type Device } from "../../api/deviceApi";
import {
  AdminContainer,
  Sidebar,
  LogoContainer,
  LogoIcon,
  AppTitle,
  AppSubtitle,
  AdminProfileCardWrapper,
  AdminProfileCard,
  AdminAvatar,
  AdminInfoContainer,
  AdminName,
  AdminEmail,
  NavigationSection,
  NavigationHeading,
  ActiveNavLink,
  InactiveNavRouterLink,
  MainContent,
  PageHeader,
  PageTitleContainer,
  PageTitle,
  PageSubtitle,
  ActionButtonsContainer,
  AddUserButton,
  AddDeviceButton,
  SummaryCardsContainer,
  SummaryCardTeal,
  SummaryCardPink,
  SummaryCardYellow,
  SummaryCardGreen,
  SummaryIconContainer,
  SummaryIcon,
  SummaryValue,
  SummaryLabel,
  TabsSearchContainer,
  TabsContainer,
  ActiveTab,
  InactiveTab,
  SearchField,
  StyledTableContainer,
  StyledTable,
  StyledTableHeadCell,
  StyledTableCell,
  StatusChipActive,
  StatusChipSuspended,
  StatusChipPending,
  ActionsContainer,
  EditActionButton,
  ViewActionButton,
  DeleteActionButton,
  StatusDotGreen,
  StatusDotPink,
  StatusDotYellow,
  StyledDialog,
  StyledDialogTitle,
  StyledDialogContent,
  StyledDialogActions,
  DialogTextField,
  DialogPrimaryButton,
  DialogCancelButton,
} from "./StyledComponents";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "NEXUS - Admin Console" },
    { name: "description", content: "NEXUS Administrative Control Panel" },
  ];
}

export default function Admin() {
  const location = useLocation();
  const isDashboard = location.pathname === "/admin" || location.pathname === "/admin/";
  const [activeTab, setActiveTab] = useState<"users" | "devices">("users");
  const [searchQuery, setSearchQuery] = useState("");
  const [users, setUsers] = useState<User[]>([]);
  const [devices, setDevices] = useState<Device[]>([]);
  const [loading, setLoading] = useState(true);

  // Summary stats
  const [totalUsers, setTotalUsers] = useState(0);
  const [activeDevices, setActiveDevices] = useState(0);
  const [pendingApprovals, setPendingApprovals] = useState(0);
  const [uptime, setUptime] = useState("99.9%");

  // Modal states
  const [addUserOpen, setAddUserOpen] = useState(false);
  const [addDeviceOpen, setAddDeviceOpen] = useState(false);
  
  // Form states for Add User
  const [userForm, setUserForm] = useState({
    fullName: "",
    email: "",
    password: "",
  });

  // Form states for Add Device
  const [deviceForm, setDeviceForm] = useState({
    name: "",
    type: "",
    description: "",
  });

  useEffect(() => {
    // Only run on client side
    if (typeof window !== "undefined") {
      loadData();
    }
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [usersData, devicesData] = await Promise.all([
        userApi.getAllUsers(),
        deviceApi.getAllDevices(),
      ]);
      setUsers(usersData);
      setDevices(devicesData);
      setTotalUsers(usersData.length);
      setActiveDevices(devicesData.length);
      // Simulate pending approvals - in real app, this would come from API
      setPendingApprovals(12);
    } catch (error) {
      console.error("Error loading data:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteUser = async (userId: string) => {
    if (window.confirm("Are you sure you want to delete this user?")) {
      try {
        await userApi.deleteUser(userId);
        await loadData();
      } catch (error) {
        console.error("Error deleting user:", error);
      }
    }
  };

  const handleDeleteDevice = async (deviceId: string) => {
    if (window.confirm("Are you sure you want to delete this device?")) {
      try {
        await deviceApi.deleteDevice(deviceId);
        await loadData();
      } catch (error) {
        console.error("Error deleting device:", error);
      }
    }
  };

  const handleAddUser = async () => {
    try {
      await userApi.createUser({
        fullName: userForm.fullName,
        email: userForm.email,
      });
      setAddUserOpen(false);
      setUserForm({ fullName: "", email: "", password: "" });
      await loadData();
    } catch (error) {
      console.error("Error creating user:", error);
      alert("Failed to create user. Please try again.");
    }
  };

  const handleAddDevice = async () => {
    try {
      await deviceApi.createDevice({
        name: deviceForm.name,
        type: deviceForm.type,
        description: deviceForm.description,
      });
      setAddDeviceOpen(false);
      setDeviceForm({ name: "", type: "", description: "" });
      await loadData();
    } catch (error) {
      console.error("Error creating device:", error);
      alert("Failed to create device. Please try again.");
    }
  };

  const filteredUsers = users.filter((user) =>
    user.fullName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    user.email.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const filteredDevices = devices.filter((device) =>
    device.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    device.type?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const ShieldSVG = () => (
    <svg
      width="28"
      height="28"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M12 2L4 5V11C4 16.55 7.16 21.74 12 23C16.84 21.74 20 16.55 20 11V5L12 2Z"
        fill="white"
      />
    </svg>
  );

  const getUserStatus = (user: User): "ACTIVE" | "SUSPENDED" | "PENDING" => {
    // In real app, this would come from user data
    // For demo, randomly assign status
    const index = users.indexOf(user);
    if (index % 3 === 0) return "ACTIVE";
    if (index % 3 === 1) return "SUSPENDED";
    return "PENDING";
  };

  return (
    <AdminContainer>
      <Sidebar>
        <LogoContainer>
          <LogoIcon>
            <ShieldSVG />
          </LogoIcon>
          <AppTitle>NEXUS</AppTitle>
          <AppSubtitle>ADMIN CONSOLE</AppSubtitle>
        </LogoContainer>

        <AdminProfileCardWrapper>
          <AdminProfileCard>
            <AdminAvatar>AD</AdminAvatar>
            <AdminInfoContainer>
              <AdminName>Admin Sarah</AdminName>
              <AdminEmail>admin@nexus.com</AdminEmail>
            </AdminInfoContainer>
          </AdminProfileCard>
        </AdminProfileCardWrapper>

        <NavigationSection>
          <NavigationHeading>ADMIN CONTROLS</NavigationHeading>
          {isDashboard ? (
            <ActiveNavLink startIcon={<DashboardIcon />} fullWidth>
              Dashboard
            </ActiveNavLink>
          ) : (
            <InactiveNavRouterLink to="/admin">
              <DashboardIcon />
              Dashboard
            </InactiveNavRouterLink>
          )}
          <InactiveNavRouterLink to="/admin/user-management">
            <PeopleIcon />
            User Management
          </InactiveNavRouterLink>
          <InactiveNavRouterLink to="/admin/device-management">
            <ComputerIcon />
            Device Management
          </InactiveNavRouterLink>
          <InactiveNavRouterLink to="/admin/audit-logs">
            <DescriptionIcon />
            Audit Logs
          </InactiveNavRouterLink>
          <InactiveNavRouterLink to="/admin/settings">
            <SettingsIcon />
            Settings
          </InactiveNavRouterLink>
        </NavigationSection>
      </Sidebar>

      <MainContent>
        {isDashboard ? (
          <>
            <PageHeader>
              <PageTitleContainer>
                <PageTitle>SYSTEM OVERVIEW</PageTitle>
                <PageSubtitle>
                  Administrative control panel for user and device management
                </PageSubtitle>
              </PageTitleContainer>
              <ActionButtonsContainer>
                <AddUserButton
                  startIcon={<PersonAddIcon />}
                  onClick={() => setAddUserOpen(true)}
                >
                  ADD USER
                </AddUserButton>
                <AddDeviceButton
                  startIcon={<AddCircleIcon />}
                  onClick={() => setAddDeviceOpen(true)}
                >
                  ADD DEVICE
                </AddDeviceButton>
              </ActionButtonsContainer>
            </PageHeader>

            <SummaryCardsContainer>
              <SummaryCardTeal>
                <SummaryIconContainer>
                  <SummaryIcon sx={{ color: "#00ffff" }}>
                    <PeopleOutlineIcon />
                  </SummaryIcon>
                </SummaryIconContainer>
                <SummaryValue>{totalUsers}</SummaryValue>
                <SummaryLabel>+23 this week</SummaryLabel>
              </SummaryCardTeal>

              <SummaryCardPink>
                <SummaryIconContainer>
                  <SummaryIcon sx={{ color: "#ff00ff" }}>
                    <DevicesIcon />
                  </SummaryIcon>
                </SummaryIconContainer>
                <SummaryValue>{activeDevices}</SummaryValue>
                <SummaryLabel>89% online</SummaryLabel>
              </SummaryCardPink>

              <SummaryCardYellow>
                <SummaryIconContainer>
                  <SummaryIcon sx={{ color: "#ffff00" }}>
                    <ScheduleIcon />
                  </SummaryIcon>
                </SummaryIconContainer>
                <SummaryValue>{pendingApprovals}</SummaryValue>
                <SummaryLabel>Requires attention</SummaryLabel>
              </SummaryCardYellow>

              <SummaryCardGreen>
                <SummaryIconContainer>
                  <SummaryIcon sx={{ color: "#00ff00" }}>
                    <FavoriteIcon />
                  </SummaryIcon>
                </SummaryIconContainer>
                <SummaryValue>{uptime}</SummaryValue>
                <SummaryLabel>All systems operational</SummaryLabel>
              </SummaryCardGreen>
            </SummaryCardsContainer>

            <TabsSearchContainer>
              <TabsContainer>
                {activeTab === "users" ? (
                  <ActiveTab onClick={() => setActiveTab("users")}>
                    USERS
                  </ActiveTab>
                ) : (
                  <InactiveTab onClick={() => setActiveTab("users")}>
                    USERS
                  </InactiveTab>
                )}
                {activeTab === "devices" ? (
                  <ActiveTab onClick={() => setActiveTab("devices")}>
                    DEVICES
                  </ActiveTab>
                ) : (
                  <InactiveTab onClick={() => setActiveTab("devices")}>
                    DEVICES
                  </InactiveTab>
                )}
              </TabsContainer>
              <SearchField
                placeholder={
                  activeTab === "users" ? "Search users..." : "Search devices..."
                }
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <SearchIcon />
                    </InputAdornment>
                  ),
                }}
              />
            </TabsSearchContainer>

            <StyledTableContainer>
              <StyledTable>
                <TableHead>
                  <TableRow>
                    <StyledTableHeadCell>NAME</StyledTableHeadCell>
                    <StyledTableHeadCell>EMAIL</StyledTableHeadCell>
                    <StyledTableHeadCell>STATUS</StyledTableHeadCell>
                    <StyledTableHeadCell>ACTIONS</StyledTableHeadCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {activeTab === "users" ? (
                    loading ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          Loading...
                        </StyledTableCell>
                      </TableRow>
                    ) : filteredUsers.length === 0 ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          No users found
                        </StyledTableCell>
                      </TableRow>
                    ) : (
                      filteredUsers.map((user) => {
                        const status = getUserStatus(user);
                        return (
                          <TableRow key={user.id}>
                            <StyledTableCell>{user.fullName}</StyledTableCell>
                            <StyledTableCell>{user.email}</StyledTableCell>
                            <StyledTableCell>
                              {status === "ACTIVE" && (
                                <StatusChipActive
                                  icon={<StatusDotGreen />}
                                  label="ACTIVE"
                                  size="small"
                                />
                              )}
                              {status === "SUSPENDED" && (
                                <StatusChipSuspended
                                  icon={<StatusDotPink />}
                                  label="SUSPENDED"
                                  size="small"
                                />
                              )}
                              {status === "PENDING" && (
                                <StatusChipPending
                                  icon={<StatusDotYellow />}
                                  label="PENDING"
                                  size="small"
                                />
                              )}
                            </StyledTableCell>
                            <StyledTableCell>
                              <ActionsContainer>
                                <EditActionButton>
                                  <EditIcon />
                                </EditActionButton>
                                <ViewActionButton>
                                  <VisibilityIcon />
                                </ViewActionButton>
                                <DeleteActionButton onClick={() => handleDeleteUser(user.id)}>
                                  <DeleteIcon />
                                </DeleteActionButton>
                              </ActionsContainer>
                            </StyledTableCell>
                          </TableRow>
                        );
                      })
                    )
                  ) : (
                    loading ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          Loading...
                        </StyledTableCell>
                      </TableRow>
                    ) : filteredDevices.length === 0 ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          No devices found
                        </StyledTableCell>
                      </TableRow>
                    ) : (
                      filteredDevices.map((device) => (
                        <TableRow key={device.id}>
                          <StyledTableCell>{device.name || "Unnamed Device"}</StyledTableCell>
                          <StyledTableCell>{device.type || "Unknown"}</StyledTableCell>
                          <StyledTableCell>
                            <StatusChipActive
                              icon={<StatusDotGreen />}
                              label="ACTIVE"
                              size="small"
                            />
                          </StyledTableCell>
                          <StyledTableCell>
                            <ActionsContainer>
                              <EditActionButton>
                                <EditIcon />
                              </EditActionButton>
                              <ViewActionButton>
                                <VisibilityIcon />
                              </ViewActionButton>
                              <DeleteActionButton onClick={() => handleDeleteDevice(device.id)}>
                                <DeleteIcon />
                              </DeleteActionButton>
                            </ActionsContainer>
                          </StyledTableCell>
                        </TableRow>
                      ))
                    )
                  )}
                </TableBody>
              </StyledTable>
            </StyledTableContainer>
          </>
        ) : (
          <Outlet />
        )}

        {/* Add User Modal */}
        <StyledDialog
          open={addUserOpen}
          onClose={() => setAddUserOpen(false)}
          maxWidth="sm"
          fullWidth
        >
          <StyledDialogTitle>ADD NEW USER</StyledDialogTitle>
          <StyledDialogContent>
            <DialogTextField
              fullWidth
              label="Full Name"
              value={userForm.fullName}
              onChange={(e) =>
                setUserForm({ ...userForm, fullName: e.target.value })
              }
              variant="outlined"
            />
            <DialogTextField
              fullWidth
              label="Email"
              type="email"
              value={userForm.email}
              onChange={(e) =>
                setUserForm({ ...userForm, email: e.target.value })
              }
              variant="outlined"
            />
            <DialogTextField
              fullWidth
              label="Password"
              type="password"
              value={userForm.password}
              onChange={(e) =>
                setUserForm({ ...userForm, password: e.target.value })
              }
              variant="outlined"
            />
          </StyledDialogContent>
          <StyledDialogActions>
            <DialogCancelButton onClick={() => setAddUserOpen(false)}>
              CANCEL
            </DialogCancelButton>
            <DialogPrimaryButton
              onClick={handleAddUser}
              disabled={!userForm.fullName || !userForm.email || !userForm.password}
            >
              CREATE USER
            </DialogPrimaryButton>
          </StyledDialogActions>
        </StyledDialog>

        {/* Add Device Modal */}
        <StyledDialog
          open={addDeviceOpen}
          onClose={() => setAddDeviceOpen(false)}
          maxWidth="sm"
          fullWidth
        >
          <StyledDialogTitle>ADD NEW DEVICE</StyledDialogTitle>
          <StyledDialogContent>
            <DialogTextField
              fullWidth
              label="Device Name"
              value={deviceForm.name}
              onChange={(e) =>
                setDeviceForm({ ...deviceForm, name: e.target.value })
              }
              variant="outlined"
            />
            <DialogTextField
              fullWidth
              label="Device Type"
              value={deviceForm.type}
              onChange={(e) =>
                setDeviceForm({ ...deviceForm, type: e.target.value })
              }
              variant="outlined"
            />
            <DialogTextField
              fullWidth
              label="Description"
              value={deviceForm.description}
              onChange={(e) =>
                setDeviceForm({ ...deviceForm, description: e.target.value })
              }
              variant="outlined"
              multiline
              rows={3}
            />
          </StyledDialogContent>
          <StyledDialogActions>
            <DialogCancelButton onClick={() => setAddDeviceOpen(false)}>
              CANCEL
            </DialogCancelButton>
            <DialogPrimaryButton
              onClick={handleAddDevice}
              disabled={!deviceForm.name || !deviceForm.type}
            >
              CREATE DEVICE
            </DialogPrimaryButton>
          </StyledDialogActions>
        </StyledDialog>
      </MainContent>
    </AdminContainer>
  );
}

