import { useState, useEffect } from "react";
import { Outlet, useLocation, useNavigate } from "react-router";
// @ts-expect-error - Route types are generated by React Router
import type { Route } from "../+types/admin";
import { InputAdornment, TableHead, TableBody, TableRow, Box } from "@mui/material";
import {
  Dashboard as DashboardIcon,
  People as PeopleIcon,
  Computer as ComputerIcon,
  Description as DescriptionIcon,
  Settings as SettingsIcon,
  PersonAdd as PersonAddIcon,
  AddCircle as AddCircleIcon,
  Search as SearchIcon,
  Edit as EditIcon,
  Visibility as VisibilityIcon,
  Delete as DeleteIcon,
  PeopleOutline as PeopleOutlineIcon,
  Devices as DevicesIcon,
  Schedule as ScheduleIcon,
  Favorite as FavoriteIcon,
  Logout as LogoutIcon,
} from "@mui/icons-material";
import { userApi, type User } from "../../api/userApi";
import { deviceApi, type Device } from "../../api/deviceApi";
import { tokenStorage } from "../../api/tokenStorage";
import {
  AdminContainer,
  Sidebar,
  LogoContainer,
  LogoIcon,
  AppTitle,
  AppSubtitle,
  AdminProfileCardWrapper,
  AdminProfileCard,
  AdminAvatar,
  AdminInfoContainer,
  AdminName,
  AdminEmail,
  NavigationSection,
  NavigationHeading,
  ActiveNavLink,
  InactiveNavRouterLink,
  MainContent,
  PageHeader,
  PageTitleContainer,
  PageTitle,
  PageSubtitle,
  ActionButtonsContainer,
  AddUserButton,
  AddDeviceButton,
  SummaryCardsContainer,
  SummaryCardTeal,
  SummaryCardPink,
  SummaryCardYellow,
  SummaryCardGreen,
  SummaryIconContainer,
  SummaryIcon,
  SummaryValue,
  SummaryLabel,
  TabsSearchContainer,
  TabsContainer,
  ActiveTab,
  InactiveTab,
  SearchField,
  StyledTableContainer,
  StyledTable,
  StyledTableHeadCell,
  StyledTableCell,
  StatusChipActive,
  StatusChipSuspended,
  StatusChipPending,
  ActionsContainer,
  EditActionButton,
  ViewActionButton,
  DeleteActionButton,
  StatusDotGreen,
  StatusDotPink,
  StatusDotYellow,
  StyledDialog,
  StyledDialogTitle,
  StyledDialogContent,
  StyledDialogActions,
  DialogTextField,
  DialogPrimaryButton,
  DialogCancelButton,
  DialogAutocomplete,
  UserInfoSection,
  DialogUserName,
  DialogUserEmail,
  DeviceListTitle,
  DeviceListContainer,
  DeviceItemCard,
  DeviceItemInfo,
  DeviceItemName,
  DeviceItemType,
  EmptyDevicesMessage,
  LogoutButton,
} from "./StyledComponents";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "NEXUS - Admin Console" },
    { name: "description", content: "NEXUS Administrative Control Panel" },
  ];
}

export default function Admin() {
  const location = useLocation();
  const navigate = useNavigate();
  const isDashboard = location.pathname === "/admin" || location.pathname === "/admin/";
  const [activeTab, setActiveTab] = useState<"users" | "devices">("users");
  const [searchQuery, setSearchQuery] = useState("");
  const [users, setUsers] = useState<User[]>([]);
  const [devices, setDevices] = useState<Device[]>([]);
  const [loading, setLoading] = useState(true);
  const [currentUser, setCurrentUser] = useState<User | null>(null);

  // Summary stats
  const [totalUsers, setTotalUsers] = useState(0);
  const [activeDevices, setActiveDevices] = useState(0);

  // Modal states
  const [addUserOpen, setAddUserOpen] = useState(false);
  const [addDeviceOpen, setAddDeviceOpen] = useState(false);
  const [userDevicesOpen, setUserDevicesOpen] = useState(false);
  
  // Form states for Add User
  const [userForm, setUserForm] = useState({
    fullName: "",
    email: "",
    password: "",
  });

  // Form states for Add Device
  const [deviceForm, setDeviceForm] = useState({
    name: "",
    type: "",
    description: "",
  });

  const [isEditingUser, setIsEditingUser] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const [isEditingDevice, setIsEditingDevice] = useState(false);
  const [editingDevice, setEditingDevice] = useState<Device | null>(null);
  
  // User devices management
  const [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [userDevices, setUserDevices] = useState<Device[]>([]);
  const [selectedDeviceToAdd, setSelectedDeviceToAdd] = useState<Device | null>(null);
  const [loadingUserDevices, setLoadingUserDevices] = useState(false);

  useEffect(() => {
    // Only run on client side
    if (typeof window !== "undefined") {
      loadData();
    }
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [usersData, devicesData, currentUserData] = await Promise.all([
        userApi.getAllUsers(),
        deviceApi.getAllDevices(),
        userApi.getUserById(tokenStorage.getUserId() || ""),
      ]);
      setUsers(usersData);
      setDevices(devicesData);
      setTotalUsers(usersData.length);
      setActiveDevices(devicesData.length);
      setCurrentUser(currentUserData);
    } catch (error) {
      console.error("Error loading data:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteUser = async (userId: string) => {
    if (window.confirm("Are you sure you want to delete this user?")) {
      try {
        await userApi.deleteUser(userId);
        await loadData();
      } catch (error) {
        console.error("Error deleting user:", error);
      }
    }
  };

  const handleDeleteDevice = async (deviceId: string) => {
    if (window.confirm("Are you sure you want to delete this device?")) {
      try {
        await deviceApi.deleteDevice(deviceId);
        await loadData();
      } catch (error) {
        console.error("Error deleting device:", error);
      }
    }
  };

  const handleAddUser = async () => {
    try {
      await userApi.createUser({
        fullName: userForm.fullName,
        email: userForm.email,
      });
      setAddUserOpen(false);
      setUserForm({ fullName: "", email: "", password: "" });
      await loadData();
    } catch (error) {
      console.error("Error creating user:", error);
      alert("Failed to create user. Please try again.");
    }
  };

  const handleAddDevice = async () => {
    try {
      await deviceApi.createDevice({
        name: deviceForm.name,
        type: deviceForm.type,
        description: deviceForm.description,
      });
      setAddDeviceOpen(false);
      setDeviceForm({ name: "", type: "", description: "" });
      await loadData();
    } catch (error) {
      console.error("Error creating device:", error);
      alert("Failed to create device. Please try again.");
    }
  };

  const handleEditUser = async (userId: string) => {
    try{
      await userApi.updateUser({
        id: userId,
        fullName: userForm.fullName,
        email: userForm.email,
      });
      setIsEditingUser(false);
      setEditingUser(null);
      setUserForm({ fullName: "", email: "", password: "" });
      setAddUserOpen(false);
      await loadData();
    } catch (error) {
      console.error("Error editing user:", error);
      alert("Failed to edit user. Please try again.");
    }
  };

  const handleEditDevice = async (deviceId: string) => {
    try{
      await deviceApi.updateDevice({
        id: deviceId,
        name: deviceForm.name,
        type: deviceForm.type,
      });
      setIsEditingDevice(false);
      setEditingDevice(null);
      setDeviceForm({ name: "", type: "", description: "" });
      setAddDeviceOpen(false);
      await loadData();
    }
    catch (error) {
      console.error("Error editing device:", error);
      alert("Failed to edit device. Please try again.");
    }
  }

  const handleOpenUserDevices = async (user: User) => {
    setSelectedUser(user);
    setUserDevicesOpen(true);
    setLoadingUserDevices(true);
    try {
      const devices = await deviceApi.getDevicesForUser(user.id);
      setUserDevices(devices);
    } catch (error) {
      console.error("Error loading user devices:", error);
      alert("Failed to load user devices. Please try again.");
      setUserDevices([]);
    } finally {
      setLoadingUserDevices(false);
    }
  };

  const handleAddDeviceToUser = async () => {
    if (!selectedUser || !selectedDeviceToAdd) return;
    
    try {
      await deviceApi.addDeviceForUser({
        userId: selectedUser.id,
        deviceId: selectedDeviceToAdd.id,
      });
      // Reload user devices
      const devices = await deviceApi.getDevicesForUser(selectedUser.id);
      setUserDevices(devices);
      setSelectedDeviceToAdd(null);
    } catch (error) {
      console.error("Error adding device to user:", error);
      alert("Failed to add device to user. Please try again.");
    }
  };

  const handleRemoveDeviceFromUser = async (deviceId: string) => {
    if (!selectedUser) return;
    
    if (!window.confirm("Are you sure you want to remove this device from the user?")) {
      return;
    }
    
    try {
      await deviceApi.removeDeviceFromUser(selectedUser.id, deviceId);
      // Reload user devices
      const devices = await deviceApi.getDevicesForUser(selectedUser.id);
      setUserDevices(devices);
    } catch (error) {
      console.error("Error removing device from user:", error);
      alert("Failed to remove device from user. Please try again.");
    }
  };

  // Get available devices (devices not already assigned to user)
  const getAvailableDevices = () => {
    if (!selectedUser) return devices;
    const assignedDeviceIds = userDevices.map(d => d.id);
    return devices.filter(device => !assignedDeviceIds.includes(device.id));
  };

  const filteredUsers = users.filter((user) =>
    user.fullName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    user.email.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const filteredDevices = devices.filter((device) =>
    device.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    device.type?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const ShieldSVG = () => (
    <svg
      width="28"
      height="28"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M12 2L4 5V11C4 16.55 7.16 21.74 12 23C16.84 21.74 20 16.55 20 11V5L12 2Z"
        fill="white"
      />
    </svg>
  );

  const getUserStatus = (user: User): "ACTIVE" | "SUSPENDED" | "PENDING" => {
    // In real app, this would come from user data
    // For demo, randomly assign status
    const index = users.indexOf(user);
    if (index % 3 === 0) return "ACTIVE";
    if (index % 3 === 1) return "SUSPENDED";
    return "PENDING";
  };

  return (
    <AdminContainer>
      <Sidebar>
        <LogoContainer>
          <LogoIcon>
            <ShieldSVG />
          </LogoIcon>
          <AppTitle>NEXUS</AppTitle>
          <AppSubtitle>ADMIN CONSOLE</AppSubtitle>
        </LogoContainer>

        <AdminProfileCardWrapper>
          <AdminProfileCard>
            <AdminAvatar>AD</AdminAvatar>
            <AdminInfoContainer>
              <AdminName>{currentUser?.fullName}</AdminName>
              <AdminEmail>{currentUser?.email}</AdminEmail>
            </AdminInfoContainer>
          </AdminProfileCard>
        </AdminProfileCardWrapper>

        <NavigationSection>
          <NavigationHeading>ADMIN CONTROLS</NavigationHeading>
          {isDashboard ? (
            <ActiveNavLink startIcon={<DashboardIcon />} fullWidth>
              Dashboard
            </ActiveNavLink>
          ) : (
            <InactiveNavRouterLink to="/admin">
              <DashboardIcon />
              Dashboard
            </InactiveNavRouterLink>
          )}
          <InactiveNavRouterLink to="/admin/settings">
            <SettingsIcon />
            Settings
          </InactiveNavRouterLink>
        </NavigationSection>

        <LogoutButton
          startIcon={<LogoutIcon />}
          fullWidth
          onClick={() => {
            tokenStorage.clearToken();
            navigate("/login");
          }}
        >
          LOGOUT
        </LogoutButton>
      </Sidebar>

      <MainContent>
        {isDashboard ? (
          <>
            <PageHeader>
              <PageTitleContainer>
                <PageTitle>SYSTEM OVERVIEW</PageTitle>
                <PageSubtitle>
                  Administrative control panel for user and device management
                </PageSubtitle>
              </PageTitleContainer>
              <ActionButtonsContainer>
                <AddUserButton
                  startIcon={<PersonAddIcon />}
                  onClick={() => {
                    setIsEditingUser(false);
                    setEditingUser(null);
                    setUserForm({ fullName: "", email: "", password: "" });
                    setAddUserOpen(true);
                  }}
                >
                  ADD USER
                </AddUserButton>
                <AddDeviceButton
                  startIcon={<AddCircleIcon />}
                  onClick={() => {
                    setIsEditingDevice(false);
                    setEditingDevice(null);
                    setDeviceForm({ name: "", type: "", description: "" });
                    setAddDeviceOpen(true);
                  }}
                >
                  ADD DEVICE
                </AddDeviceButton>
              </ActionButtonsContainer>
            </PageHeader>

            <SummaryCardsContainer>
              <SummaryCardTeal>
                <SummaryIconContainer>
                  <SummaryIcon sx={{ color: "#00ffff" }}>
                    <PeopleOutlineIcon />
                  </SummaryIcon>
                </SummaryIconContainer>
                <SummaryValue>{totalUsers}</SummaryValue>
              </SummaryCardTeal>

              <SummaryCardPink>
                <SummaryIconContainer>
                  <SummaryIcon sx={{ color: "#ff00ff" }}>
                    <DevicesIcon />
                  </SummaryIcon>
                </SummaryIconContainer>
                <SummaryValue>{activeDevices}</SummaryValue>
              </SummaryCardPink>

              <SummaryCardGreen>
                <SummaryIconContainer>
                  <SummaryIcon sx={{ color: "#00ff00" }}>
                    <FavoriteIcon />
                  </SummaryIcon>
                </SummaryIconContainer>
                <SummaryValue>99.9%</SummaryValue>
                <SummaryLabel>All systems operational</SummaryLabel>
              </SummaryCardGreen>
            </SummaryCardsContainer>

            <TabsSearchContainer>
              <TabsContainer>
                {activeTab === "users" ? (
                  <ActiveTab onClick={() => setActiveTab("users")}>
                    USERS
                  </ActiveTab>
                ) : (
                  <InactiveTab onClick={() => setActiveTab("users")}>
                    USERS
                  </InactiveTab>
                )}
                {activeTab === "devices" ? (
                  <ActiveTab onClick={() => setActiveTab("devices")}>
                    DEVICES
                  </ActiveTab>
                ) : (
                  <InactiveTab onClick={() => setActiveTab("devices")}>
                    DEVICES
                  </InactiveTab>
                )}
              </TabsContainer>
            </TabsSearchContainer>

            <StyledTableContainer>
              <StyledTable>
                <TableHead>
                  <TableRow>
                    <StyledTableHeadCell>NAME</StyledTableHeadCell>
                    <StyledTableHeadCell>{activeTab === "users" ? "EMAIL" : "TYPE"}</StyledTableHeadCell>
                    <StyledTableHeadCell>STATUS</StyledTableHeadCell>
                    <StyledTableHeadCell>ACTIONS</StyledTableHeadCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {activeTab === "users" ? (
                    loading ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          Loading...
                        </StyledTableCell>
                      </TableRow>
                    ) : filteredUsers.length === 0 ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          No users found
                        </StyledTableCell>
                      </TableRow>
                    ) : (
                      filteredUsers.map((user) => {
                        const status = getUserStatus(user);
                        return (
                          <TableRow key={user.id}>
                            <StyledTableCell>{user.fullName}</StyledTableCell>
                            <StyledTableCell>{user.email}</StyledTableCell>
                            <StyledTableCell>
                              {status === "ACTIVE" && (
                                <StatusChipActive
                                  icon={<StatusDotGreen />}
                                  label="ACTIVE"
                                  size="small"
                                />
                              )}
                              {status === "SUSPENDED" && (
                                <StatusChipSuspended
                                  icon={<StatusDotPink />}
                                  label="SUSPENDED"
                                  size="small"
                                />
                              )}
                              {status === "PENDING" && (
                                <StatusChipPending
                                  icon={<StatusDotYellow />}
                                  label="PENDING"
                                  size="small"
                                />
                              )}
                            </StyledTableCell>
                            <StyledTableCell>
                              <ActionsContainer>
                                <ViewActionButton onClick={() => handleOpenUserDevices(user)}>
                                  <VisibilityIcon />
                                </ViewActionButton>
                                <EditActionButton onClick={() => { 
                                  setIsEditingUser(true); 
                                  setEditingUser(user); 
                                  setUserForm({ 
                                    fullName: user.fullName, 
                                    email: user.email, 
                                    password: "" 
                                  }); 
                                  setAddUserOpen(true); 
                                }}>
                                  <EditIcon />
                                </EditActionButton>
                                <DeleteActionButton onClick={() => handleDeleteUser(user.id)}>
                                  <DeleteIcon />
                                </DeleteActionButton>
                              </ActionsContainer>
                            </StyledTableCell>
                          </TableRow>
                        );
                      })
                    )
                  ) : (
                    loading ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          Loading...
                        </StyledTableCell>
                      </TableRow>
                    ) : filteredDevices.length === 0 ? (
                      <TableRow>
                        <StyledTableCell colSpan={4} align="center">
                          No devices found
                        </StyledTableCell>
                      </TableRow>
                    ) : (
                      filteredDevices.map((device) => (
                        <TableRow key={device.id}>
                          <StyledTableCell>{device.name || "Unnamed Device"}</StyledTableCell>
                          <StyledTableCell>{device.type || "Unknown"}</StyledTableCell>
                          <StyledTableCell>
                            <StatusChipActive
                              icon={<StatusDotGreen />}
                              label="ACTIVE"
                              size="small"
                            />
                          </StyledTableCell>
                          <StyledTableCell>
                              <ActionsContainer>
                              <EditActionButton onClick={() => { 
                                setIsEditingDevice(true); 
                                setEditingDevice(device); 
                                setDeviceForm({ 
                                  name: device.name || "", 
                                  type: device.type || "", 
                                  description: device.description || "" 
                                }); 
                                setAddDeviceOpen(true); 
                              }}>
                                  <EditIcon />
                              </EditActionButton>
                              <DeleteActionButton onClick={() => handleDeleteDevice(device.id)}>
                                  <DeleteIcon />
                              </DeleteActionButton>
                            </ActionsContainer>
                          </StyledTableCell>
                        </TableRow>
                      ))
                    )
                  )}
                </TableBody>
              </StyledTable>
            </StyledTableContainer>
          </>
        ) : (
          <Outlet />
        )}

        {/* Add User Modal */}
        <StyledDialog
          open={addUserOpen}
          onClose={() => { 
            setAddUserOpen(false); 
            setIsEditingUser(false); 
            setEditingUser(null); 
            setUserForm({ fullName: "", email: "", password: "" }); 
          }}
          maxWidth="sm"
          fullWidth
        >
          <StyledDialogTitle>{isEditingUser ? "EDIT USER" : "ADD NEW USER"}</StyledDialogTitle>
          <StyledDialogContent>
            <DialogTextField
              fullWidth
              label="Full Name"
              value={userForm.fullName}
              onChange={(e) =>
                setUserForm({ ...userForm, fullName: e.target.value })
              }
              variant="outlined"
            />
            <DialogTextField
              fullWidth
              label="Email"
              type="email"
              value={userForm.email}
              onChange={(e) =>
                setUserForm({ ...userForm, email: e.target.value })
              }
              variant="outlined"
              disabled={isEditingUser}
            />
            {!isEditingUser && (
              <DialogTextField
                fullWidth
                label="Password"
                type="password"
                value={userForm.password}
                onChange={(e) =>
                  setUserForm({ ...userForm, password: e.target.value })
                }
                variant="outlined"
              />
            )}
          </StyledDialogContent>
          <StyledDialogActions>
            <DialogCancelButton onClick={() => { 
              setAddUserOpen(false); 
              setIsEditingUser(false); 
              setEditingUser(null); 
              setUserForm({ fullName: "", email: "", password: "" }); 
            }}>
              CANCEL
            </DialogCancelButton>
            <DialogPrimaryButton
              onClick={() => isEditingUser ? handleEditUser(editingUser?.id || "") : handleAddUser()}
              disabled={!userForm.fullName || !userForm.email || (!isEditingUser && !userForm.password)}
            >
              {isEditingUser ? "UPDATE USER" : "CREATE USER"}
            </DialogPrimaryButton>
          </StyledDialogActions>
        </StyledDialog>

        {/* Add Device Modal */}
        <StyledDialog
          open={addDeviceOpen}
          onClose={() => { 
            setAddDeviceOpen(false); 
            setIsEditingDevice(false); 
            setEditingDevice(null); 
            setDeviceForm({ name: "", type: "", description: "" }); 
          }}
          maxWidth="sm"
          fullWidth
        >
          <StyledDialogTitle>{isEditingDevice ? "EDIT DEVICE" : "ADD NEW DEVICE"}</StyledDialogTitle>
          <StyledDialogContent>
            <DialogTextField
              fullWidth
              label="Device Name"
              value={deviceForm.name}
              onChange={(e) =>
                setDeviceForm({ ...deviceForm, name: e.target.value })
              }
              variant="outlined"
            />
            <DialogTextField
              fullWidth
              label="Device Type"
              value={deviceForm.type}
              onChange={(e) =>
                setDeviceForm({ ...deviceForm, type: e.target.value })
              }
              variant="outlined"
            />
          </StyledDialogContent>
          <StyledDialogActions>
            <DialogCancelButton onClick={() => { 
              setAddDeviceOpen(false); 
              setIsEditingDevice(false); 
              setEditingDevice(null); 
              setDeviceForm({ name: "", type: "", description: "" }); 
            }}>
              CANCEL
            </DialogCancelButton>
            <DialogPrimaryButton
              onClick={() => isEditingDevice ? handleEditDevice(editingDevice?.id || "") : handleAddDevice()}
              disabled={!deviceForm.name || !deviceForm.type}
            >
              {isEditingDevice ? "UPDATE DEVICE" : "CREATE DEVICE"}
            </DialogPrimaryButton>
          </StyledDialogActions>
        </StyledDialog>

        {/* User Devices Management Modal */}
        <StyledDialog
          open={userDevicesOpen}
          onClose={() => {
            setUserDevicesOpen(false);
            setSelectedUser(null);
            setUserDevices([]);
            setSelectedDeviceToAdd(null);
          }}
          maxWidth="md"
          fullWidth
        >
          <StyledDialogTitle>
            MANAGE USER DEVICES
          </StyledDialogTitle>
          <StyledDialogContent>
            {selectedUser && (
              <>
                <UserInfoSection>
                  <DialogUserName>{selectedUser.fullName}</DialogUserName>
                  <DialogUserEmail>{selectedUser.email}</DialogUserEmail>
                </UserInfoSection>

                <DeviceListTitle>CONNECTED DEVICES</DeviceListTitle>
                
                {loadingUserDevices ? (
                  <EmptyDevicesMessage>Loading devices...</EmptyDevicesMessage>
                ) : userDevices.length === 0 ? (
                  <EmptyDevicesMessage>No devices connected to this user</EmptyDevicesMessage>
                ) : (
                  <DeviceListContainer>
                    {userDevices.map((device) => (
                      <DeviceItemCard key={device.id}>
                        <DeviceItemInfo>
                          <DeviceItemName>{device.name || "Unnamed Device"}</DeviceItemName>
                          <DeviceItemType>{device.type || "Unknown Type"}</DeviceItemType>
                        </DeviceItemInfo>
                        <DeleteActionButton
                          onClick={() => handleRemoveDeviceFromUser(device.id)}
                          size="small"
                        >
                          <DeleteIcon />
                        </DeleteActionButton>
                      </DeviceItemCard>
                    ))}
                  </DeviceListContainer>
                )}

                <Box sx={{ marginTop: "24px", display: "flex", gap: "12px", alignItems: "flex-end" }}>
                  <DialogAutocomplete
                    fullWidth
                    options={getAvailableDevices()}
                    getOptionLabel={(option: unknown) => {
                      const device = option as Device;
                      return `${device.name || "Unnamed Device"} (${device.type || "Unknown"})`;
                    }}
                    value={selectedDeviceToAdd}
                    onChange={(_, newValue: unknown) => setSelectedDeviceToAdd(newValue as Device | null)}
                    isOptionEqualToValue={(option: unknown, value: unknown) => {
                      const opt = option as Device;
                      const val = value as Device;
                      return opt.id === val.id;
                    }}
                    renderInput={(params) => (
                      <DialogTextField
                        {...params}
                        label="Select Device to Add"
                        variant="outlined"
                      />
                    )}
                  />
                  <DialogPrimaryButton
                    onClick={handleAddDeviceToUser}
                    disabled={!selectedDeviceToAdd}
                  >
                    ADD
                  </DialogPrimaryButton>
                </Box>
              </>
            )}
          </StyledDialogContent>
          <StyledDialogActions>
            <DialogCancelButton
              onClick={() => {
                setUserDevicesOpen(false);
                setSelectedUser(null);
                setUserDevices([]);
                setSelectedDeviceToAdd(null);
              }}
            >
              CLOSE
            </DialogCancelButton>
          </StyledDialogActions>
        </StyledDialog>
      </MainContent>
    </AdminContainer>
  );
}

