import { Link } from "react-router";
// @ts-expect-error - Route types are generated by React Router
import type { Route } from "../+types/home";
import {
  Devices as DevicesIcon,
  Security as SecurityIcon,
  Dashboard as DashboardIcon,
  Speed as SpeedIcon,
} from "@mui/icons-material";
import {
  LandingContainer,
  BackgroundGradient,
  ContentWrapper,
  LogoContainer,
  LogoIcon,
  MainTitle,
  Subtitle,
  FeaturesGrid,
  FeatureCard,
  FeatureIconContainer,
  FeatureTitle,
  FeatureDescription,
  CTASection,
  PrimaryCTAButton,
  SecondaryCTAButton,
  StyledRouterLink,
} from "./StyledComponents";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "NEXUS - Device Management Platform" },
    {
      name: "description",
      content: "NEXUS - Secure and efficient device management platform",
    },
  ];
}

const features = [
  {
    icon: <DevicesIcon />,
    title: "Device Management",
    description:
      "Seamlessly manage and monitor all your devices from a centralized dashboard with real-time updates.",
  },
  {
    icon: <SecurityIcon />,
    title: "Secure Access",
    description:
      "Enterprise-grade security with JWT authentication and role-based access control for your peace of mind.",
  },
  {
    icon: <DashboardIcon />,
    title: "Admin Console",
    description:
      "Comprehensive administrative tools to manage users, devices, and system configurations efficiently.",
  },
  {
    icon: <SpeedIcon />,
    title: "High Performance",
    description:
      "Built with microservices architecture for scalability, reliability, and optimal performance.",
  },
];

export default function Home() {
  return (
    <LandingContainer>
      <BackgroundGradient />
      <ContentWrapper maxWidth="lg">
        <LogoContainer>
          <LogoIcon>
            <DashboardIcon />
          </LogoIcon>
          <MainTitle>NEXUS</MainTitle>
          <Subtitle>
            Advanced Device Management Platform
            <br />
            Secure • Scalable • Intelligent
          </Subtitle>
        </LogoContainer>

        <FeaturesGrid>
          {features.map((feature, index) => (
            <FeatureCard key={index}>
              <FeatureIconContainer>{feature.icon}</FeatureIconContainer>
              <FeatureTitle>{feature.title}</FeatureTitle>
              <FeatureDescription>{feature.description}</FeatureDescription>
            </FeatureCard>
          ))}
        </FeaturesGrid>

        <CTASection>
          <StyledRouterLink to="/login">
            <PrimaryCTAButton size="large">
              Get Started
            </PrimaryCTAButton>
          </StyledRouterLink>
          <SecondaryCTAButton size="large">
            Learn More
          </SecondaryCTAButton>
        </CTASection>
      </ContentWrapper>
    </LandingContainer>
  );
}

