import { useState } from "react";
import { useNavigate } from "react-router";
// @ts-expect-error - Route types are generated by React Router
import type { Route } from "../+types/login";
import { authApi } from "../../api/authApi";
import {
  Bolt as BoltIcon,
  Error as ErrorIcon,
  VisibilityOff as VisibilityOffIcon,
  Visibility as VisibilityIcon,
} from "@mui/icons-material";
import { InputAdornment, IconButton } from "@mui/material";
import {
  PageContainer,
  ContainerWrapper,
  NexusCardWrapper,
  NexusCard,
  ActiveTab,
  InactiveTab,
  TabContainer,
  LogoContainer,
  ShieldIcon,
  TitleContainer,
  MainTitle,
  Subtitle,
  FormContainer,
  InputLabel,
  InputWrapper,
  EmailTextField,
  PasswordTextField,
  FullNameTextField,
  InputIconContainer,
  EmailIconStyled,
  PrimaryButton,
  ForgotPasswordLink,
  ErrorAlert,
  ErrorIconStyled,
  DividerText,
  SecondaryText,
  SecondaryLink,
  FooterText,
  FooterRouterLink,
} from "./StyledComponents";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "NEXUS - Secure Access" },
    { name: "description", content: "Login to NEXUS Security Protocol" },
  ];
}

export default function Login() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<"login" | "signup">("login");
  const [showPassword, setShowPassword] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [fullName, setFullName] = useState("");
  const [showError, setShowError] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleTabChange = (tab: "login" | "signup") => {
    setActiveTab(tab);
    setShowError(false);
    // Clear form when switching tabs
    setEmail("");
    setPassword("");
    setFullName("");
  };

  const handleSubmit = async () => {
    if (activeTab === "login") {
      if (!email || !password) {
        setShowError(true);
        return;
      }

      try {
        setLoading(true);
        setShowError(false);
        const response = await authApi.login({ email, password });
        if (response.role === "ADMIN") {
          navigate("/admin");
        } else {
          navigate("/dashboard");
        }
      } catch (error) {
        setShowError(true);
      } finally {
        setLoading(false);
      }
    } else {
      if (!email || !password || !fullName) {
        return;
      }

      try {
        setLoading(true);
        const response = await authApi.register({ email, password, fullName });
        if (response.role === "ADMIN") {
          navigate("/admin");
        } else {
          navigate("/dashboard");
        }
      } catch (error) {
        setShowError(true);
      } finally {
        setLoading(false);
      }
    }
  };

  const handleTogglePassword = () => {
    setShowPassword(!showPassword);
  };

  const ShieldSVG = () => (
    <svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M12 2L4 5V11C4 16.55 7.16 21.74 12 23C16.84 21.74 20 16.55 20 11V5L12 2Z"
        fill="white"
        stroke="white"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );

  return (
    <PageContainer>
      <ContainerWrapper>
        <NexusCardWrapper>
          <NexusCard>
            <LogoContainer>
              <ShieldIcon>
                <ShieldSVG />
              </ShieldIcon>
              <TitleContainer>
                <MainTitle>NEXUS</MainTitle>
                <Subtitle>SECURE ACCESS</Subtitle>
              </TitleContainer>
            </LogoContainer>

            <TabContainer>
              {activeTab === "login" ? (
                <ActiveTab fullWidth onClick={() => handleTabChange("login")}>
                  LOGIN
                </ActiveTab>
              ) : (
                <InactiveTab fullWidth onClick={() => handleTabChange("login")}>
                  LOGIN
                </InactiveTab>
              )}
              {activeTab === "signup" ? (
                <ActiveTab fullWidth onClick={() => handleTabChange("signup")}>
                  SIGNUP
                </ActiveTab>
              ) : (
                <InactiveTab fullWidth onClick={() => handleTabChange("signup")}>
                  SIGNUP
                </InactiveTab>
              )}
            </TabContainer>

            <FormContainer>
              {activeTab === "signup" && (
                <>
                  <InputLabel>FULL NAME</InputLabel>
                  <InputWrapper>
                    <FullNameTextField
                      fullWidth
                      type="text"
                      placeholder="John Doe"
                      value={fullName}
                      onChange={(e) => setFullName(e.target.value)}
                    />
                    <InputIconContainer>
                      <EmailIconStyled />
                    </InputIconContainer>
                  </InputWrapper>
                </>
              )}

              <InputLabel>EMAIL ADDRESS</InputLabel>
              <InputWrapper>
                <EmailTextField
                  fullWidth
                  type="email"
                  placeholder={activeTab === "login" ? "john.doe@nexus.com" : "Enter your email"}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
                <InputIconContainer>
                  <EmailIconStyled />
                </InputIconContainer>
              </InputWrapper>

              <InputLabel>PASSWORD</InputLabel>
              <InputWrapper>
                <PasswordTextField
                  fullWidth
                  type={showPassword ? "text" : "password"}
                  placeholder="Enter your password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}        
                />
              </InputWrapper>

              {activeTab === "login" && (
                <ForgotPasswordLink
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                  }}
                >
                  Forgot Password?
                </ForgotPasswordLink>
              )}

              {showError && activeTab === "login" && (
                <ErrorAlert
                  severity="error"
                  icon={
                    <ErrorIconStyled>
                      <ErrorIcon />
                    </ErrorIconStyled>
                  }
                >
                  Invalid credentials. Please try again.
                </ErrorAlert>
              )}

              <PrimaryButton
                fullWidth
                variant="contained"
                startIcon={<BoltIcon />}
                onClick={handleSubmit}
                disabled={loading}
              >
                {loading
                  ? "PROCESSING..."
                  : activeTab === "login"
                  ? "ACCESS SYSTEM"
                  : "CREATE ACCOUNT"}
              </PrimaryButton>

              <DividerText>OR</DividerText>
              <SecondaryText>
                {activeTab === "login"
                  ? "Don't have an account? "
                  : "Already have an account? "}
                <SecondaryLink
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    handleTabChange(activeTab === "login" ? "signup" : "login");
                  }}
                >
                  {activeTab === "login" ? "Sign Up" : "Sign In"}
                </SecondaryLink>
              </SecondaryText>
            </FormContainer>

            <FooterText>
              NEXUS SECURITY PROTOCOL v2.0M
              <br />
              Privacy Terms{" "}
              <FooterRouterLink to="/">
                Support
              </FooterRouterLink>
            </FooterText>
          </NexusCard>
        </NexusCardWrapper>
      </ContainerWrapper>
    </PageContainer>
  );
}

