// @ts-expect-error - Route types are generated by React Router
import type { Route } from "../+types/dashboard.profile";
import {
  PageHeader,
  PageTitleContainer,
  PageTitle,
  PageSubtitle,
} from "./StyledComponents";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "NEXUS - Profile" },
    { name: "description", content: "User Profile Page" },
  ];
}

export default function Profile() {
  return (
    <>
      <PageHeader>
        <PageTitleContainer>
          <PageTitle>PROFILE</PageTitle>
          <PageSubtitle>Manage your account settings and preferences</PageSubtitle>
        </PageTitleContainer>
      </PageHeader>
    </>
  );
}

